### ISSUE TITLE
Extend Semantics

### ISSUE THREAD

**Issue by NET4ORCE** [bendc/frontend-guidelines#10]
I really like many of the points you've made through the guide.  :+1: 

One area of semantics that many devs, I've met, have trouble knowing is when to use `<section>` over `<article>`, vice-versa or even over `<div>`.  

You managed to side-step it by using class names on the original markup. 

Other (html5) elements like `<header>`, `<footer>`, `<hgroup>`, `<aside>` etc are self evident, but I think the guide would benefit from a brief example of where `<section>` and `<article>` should be used.

**Comment by bendc** [comment]
Thanks!

This is not a guide on how to specifically use each element of the spec. The goal is just to highlight the fact that you should benefit from HTML5's rich semantics. I'd rather keep my example short :)
