### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by mrflix** [bendc/frontend-guidelines#12]
Hello Benjamin,

why do you see hsl inferior to hex?

Hsl gives me the possibility to work with colors: if I want to tone down the color for the active state I adjust the lightness. When I want to create a slightly blue toned gray I use a hue of ~200, a saturation of ~8% and ~97% lightness.

**Comment by atadams** [comment]
+1

**Comment by richn** [comment]
+1

**Comment by bendc** [comment]
I like `HSL` per se too, but it is unfortunately pretty much useless in practice as most design tools use `HSB` instead. I often see designers getting confused because they don't realize `HSL` != `HSB`.
