### ISSUE TITLE
Why px over em? 

### ISSUE THREAD

**Issue by Kyokou** [bendc/frontend-guidelines#14]
In reference to "Favor pixels over relative units". 

I'd like to hear your reasoning, as most people I speak to prefer em over px, including my own preference. 

Also, good reading: 
http://nerd.vasilis.nl/using-pixels-polite/

**Comment by maoberlehner** [comment]
+1

**Comment by heitzke** [comment]
IMO that's why these are guidelines. While I (and we, seemingly) agree with many of them, some of these are strictly preference. 

Rem is the superior unit, but I too, have found it fairly problematic in larger projects.

**Comment by Kyokou** [comment]
Being confused by something is a very poor reason to not use it, if anything that's a good reason to learn it properly! That's a disappointing answer, but if that is where he stands, that's his choice. 

@heitzke 
I find any problems people run into stem from using em and losing track of the parent's font size. Since rem always uses the root font size, I can't imagine what difficulties might stem from it. Do you mind elaborating what was problematic?

**Comment by heitzke** [comment]
I wholeheartedly agree, but these are just his preferences. 

@Kyokou yeah that was always the issue with em. Issues are generally on larger projects where I either can't comb every commit, or the timeline is just too tight. Going back and combing through sass and removing fixed px font-sizes just wasn't worth the time to me, and it was always frustrating to have font-sizes set in different units. 

Communication on larger teams is key, sure, but I'm more so just explaining my personal experiences. On things I *can* and *want* to control, I use rem.

**Comment by joaocunha** [comment]
After [pixrem](https://github.com/robwierzbowski/node-pixrem) I can't see any reason not to favor rem over pixels.

**Comment by bendc** [comment]
[Fixed](https://github.com/bendc/frontend-guidelines#units). Thanks!
