### ISSUE TITLE
Suggestion: add classes to the HTML semantics example

### ISSUE THREAD

**Issue by rstacruz** [bendc/frontend-guidelines#18]
This example:

```html
  <article>
    <header>
      <h1>Blog post</h1>
      <p>Published: <time datetime="2015-02-21">21st Feb, 2015</time></p>
    </header>
    <p>…</p>
  </article>
```

...is probably better written with class names. Personally I would rather sway against the practice of styling plain tags (`article`, `header`) as it can lead to problems once you start scaling your site.

```html
  <article class='blog-post'>
    <header class='post-header'>
      <h1>Blog post</h1>
      <p>Published: <time datetime="2015-02-21">21st Feb, 2015</time></p>
    </header>
    <p>…</p>
  </article>
```

**Comment by bendc** [comment]
The need for specific classes is directly related to your specific project. This is just a general guideline comparing a semantic and non-semantic markup.
