### ISSUE TITLE
calc() Not fully supported 

### ISSUE THREAD

**Issue by NET4ORCE** [bendc/frontend-guidelines#24]
Also the use of `calc()`.  I know you keep cited "Standards" but this isn't fully supported and currently CR. 

<https://developer.mozilla.org/en-US/docs/Web/CSS/calc#Browser_compatibility>

Duplicate from : <https://github.com/bendc/frontend-guidelines/issues/22#issuecomment-76189301>

**Comment by bendc** [comment]
As mentioned in lots of other issues, these guidelines are based on specifications, not current browser support.
