### ISSUE TITLE
ES6 Features Unsupported In Most Browsers

### ISSUE THREAD

**Issue by kevinzweerink** [bendc/frontend-guidelines#26]
=> , Map(), const, ... (spread operator), etc are all currently unsupported ES6 features.

I think it might be unclear to many who stumble across this guide that these require transpiling and do not have wide support. Perhaps note this, or change examples to reflect current standards?

**Comment by charstarstars** [comment]
+1

**Comment by glebcha** [comment]
You can use Babel as a fallback, but using ES6 features now is a must I think.

**Comment by codeclown** [comment]
Mentioning these are ES6 features in the beginning of the JavaScript section would be good in my opinion, no harm done?

**Comment by lazychino** [comment]
:+1:

**Comment by isdampe** [comment]
Definitely should be a mention of ES6 and/or suggested ways to use a fallback.

**Comment by bendc** [comment]
What @glebcha said, basically. Also, as mentioned in many other issues, these guidelines are based on actual specs, not the always evolving browser implementations.
