### ISSUE TITLE
IE9 needs the body tag...

### ISSUE THREAD

**Issue by webdevisme** [bendc/frontend-guidelines#29]
Maybe put a caveat under this section regarding this... http://stackoverflow.com/questions/5641997/is-it-necessary-to-write-head-body-and-html-tags

**Comment by zalog** [comment]
#19 :)

**Comment by x-ji** [comment]
Yeah could probably at least add an explanation. Note that developers in developing countries are far more likely to have to face the headache of dealing with old browser compatibility, and they are many in numbers.

**Comment by webdevisme** [comment]
Lol. I'm in the UK and still deving for ie9 ;)

**Comment by bendc** [comment]
As mentioned in #19, these guidelines don't take into account the lack of support for feature X or Y on browser X or Y. It's solely based on the standard specifications.
