### ISSUE TITLE
favour px over relative units

### ISSUE THREAD

**Issue by zimok** [bendc/frontend-guidelines#3]
really sure about this?

http://css-tricks.com/why-ems/
http://css-tricks.com/forums/topic/whats-the-benefit-of-using-ems-instead-of-pxs/

**Comment by bendc** [comment]
I'm sure it's my preference yeah :p Joking aside, while relative units are theoretically superior, they're in my experience confusing and harder to work with.

**Comment by thecodezombie** [comment]
So why is this repo described as 'best practice' if you admit that the opposite is theoretically superior? It's just a bit of maths, you can even use [rem calculators](https://offroadcode.com/prototypes/rem-calculator/)!

**Comment by bendc** [comment]
Theoretically superior != superior in practice. Feel free to use relative units if you prefer :)
