### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by samcfc** [bendc/frontend-guidelines#4]
Thank your for your résumé, could you perhaps improve it with on advice that could need it, explain why your approach is better.

For JS tips, it could be very useful I think, as it is better to understand why we do such a way than just copying advices without understanding the underlaying logic.

Thanks again

**Comment by bendc** [comment]
I honestly doubt I'll have the time/motivation to explain every single section in details but let me know if there's something specific you'd like me to cover :)
