### ISSUE TITLE
Brevity

### ISSUE THREAD

**Issue by bogdansoare** [bendc/frontend-guidelines#5]
Thanks for sharing your guidelines.
Why would you suggest dropping the header & body tags?

**Comment by bendc** [comment]
You can keep them if you prefer, it's no like they won't make a big difference ;) The suggestion is just to keep your code terse in general. Less code is just easier to read.

**Comment by bogdansoare** [comment]
Thanks for the answer, makes sense.
Cheers.

**Comment by MOZGIII** [comment]
Terse is good, but by html5 spec you MUST use `head` and `body`.

Ref:
https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html
