### ISSUE TITLE
What about script async and defer?

### ISSUE THREAD

**Issue by Vheissu** [bendc/frontend-guidelines#68]
In the article under performance you mention including scripts at the bottom of the page. However, I think this is misleading. It is possible to include scripts in the header and not have them block the page through the use of async or defer.

I think it is also important to add that there are times when you don't need to include an external file. If you are including code that is a few lines, you can inline it into the page and it'll always be faster because you're avoiding a HTTP request.

I recommend using "defer" by default. [This article](http://peter.sh/experiments/asynchronous-and-deferred-javascript-execution-explained/) from 2010 actually explains what each of the attributes do and how they affect the page.

**Comment by agauniyal** [comment]
+1 and this : [link](https://www.google.co.in/search?q=load+css+async)

**Comment by bendc** [comment]
This guideline doesn't mention how it should be done, only that you shouldn't block rendering.
