### ISSUE TITLE
Hacks

### ISSUE THREAD

**Issue by Bit32** [bendc/frontend-guidelines#717]
Hope you don't mind me saying that the example stated for this section seems bizarre given it's relative obscurity and at best, nascent support. 

Such an odd choice of property would fine (and even informative) were it not at risk of completely over shadowing the broader context. 

Perhaps another example would be better; I would of made a suggestion but due to the sections brevity it's hard to judge exactly what the broader point being made here is.

**Comment by bendc** [comment]
The point is just to illustrate the fact that you shouldn't use properties / odd notations for their side-effects.
