### ISSUE TITLE
Recursion in JS is actually bad

### ISSUE THREAD

**Issue by reg4in** [bendc/frontend-guidelines#721]
As Javascript doesn't have TCO (yet), recursion will make the browser crash when traversing big Arrays. If you cannot be completely sure the Arrays won't be too big, you should avoid it whenever possible.

**Comment by bendc** [comment]
Pretty much all the examples in the JS guidelines contain at least one feature not supported by one browser. Tail call optimization is one of them.

As mentioned in other issues, this document doesn't take current browser support into account. Eventually, all browsers will implement all these features. These guidelines are based on specs, not on the always-evolving browser landscape.

**Comment by reg4in** [comment]
Thanks for the enlightment! I didn't know that :+1:
