### ISSUE TITLE
Covering WAI-ARIA and form accessibility

### ISSUE THREAD

**Issue by vitortalaia** [bendc/frontend-guidelines#741]
Hi,

I think that would be necessary add examples of form accessibility, like the importance of `fieldset` grouping, `legend` and the correlation between labels and input fields. Also as WAI-ARIA basics covering simple roles and "described by" attribute (maybe live regions?). IMO it's a way of instigate readers to dive into this subject.

Thanks.

**Comment by scriptype** [comment]
:+1:

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by bendc** [comment]
This would go too far into implementation details. The goal here is just to give general advices illustrated by one or two simple examples. Thanks!
