### ISSUE TITLE
ArrowFunctionExpression is not supported

### ISSUE THREAD

**Issue by gouravtiwari** [bendc/frontend-guidelines#742]
Hey @bendc 
This is AWESOME list! Thanks for putting it together. There is one issue though and may be I misunderstood this one:
```javascript
const isEven = n => n % 2 == 0;
```
This throws error: SyntaxError: Unexpected token '>'
also: ArrowFunctionExpression is not supported

This seems a coffee-script syntax, is it supported in JS?

**Comment by vitortalaia** [comment]
@gouravtiwari Unfortunately the [compatibility for this specification is low](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility)... If you don't use Firefox, you can use [Babel](https://babeljs.io) or [Traceur](https://github.com/google/traceur-compiler) for transpiling it to ES5

**Comment by 6temes** [comment]
@gouravtiwari. The arrow function is Ecmascript 6, the new version of Javascript. It has not been released yet and most features are not implemented in any Browser, but you can "transpile" it to ES5 (the current Javascript) using [Traceur](https://github.com/google/traceur-compiler).

**Comment by igregson** [comment]
Agreed. Using arrow functions in a "front-end *guidelines*" writeup is pretty misleading. 

At least a simple note about it only being supported in ES6 would be helpful (for myself and likely others).

**Comment by gouravtiwari** [comment]
Thanks @vitortalaia and @6temes, I just created a PR https://github.com/bendc/frontend-guidelines/pull/747 for the same.

**Comment by vitortalaia** [comment]
:+1:
