### ISSUE TITLE
head element

### ISSUE THREAD

**Issue by ericksahara** [bendc/frontend-guidelines#745]
Hello, thank you for sharing this guideline!

I have a doubt:

> Keep your code terse. Forget about your old XHTML habits.

The element `<head>` isn't required?

**Comment by DonQuality** [comment]
Hi there, what Element ?.

**Comment by ericksahara** [comment]
The `<head>` element.

**Comment by DonQuality** [comment]
Yes, you can omit them and be technically valid, but it is generally unwise
to do so.
Good eye Erick ;).It's always better to build a solid semantic structure
and not omit any of the element tags.

**Comment by ericksahara** [comment]
Thanks for the quick reply Don :)

**Comment by DonQuality** [comment]
No problem !!!

**Comment by becarlos** [comment]
I think this guide aim to build a solid semantic structure for Frontend guys. Can you imagine to see a lot of pages without all those of elements "head", "body"?

It's better to build a solid semantic structure, why hasn't it been changed yet? Even it's being valid.

Thanks!
