### ISSUE TITLE
Both object iterations mentioned are slow. Use native for loop

### ISSUE THREAD

**Issue by swanidhi** [bendc/frontend-guidelines#752]
// bad
for (var prop in obj) {
  if (obj.hasOwnProperty(prop))
    console.log(prop);
}

// bad
Object.keys(obj).forEach(prop => console.log(prop));

//good -- fastest
keys  = Object.keys(obj);
for (var i = 0, l = keys.length; i < l; i++) {
  result = result + obj[keys[i]];
}

**Comment by misbeliever** [comment]
Hi @swanidhi, did you read the guidelines? 

# JavaScript

## Performance

      Favor readability, correctness and expressiveness over performance. 


  
and forEach variation is most readable at most cases;

**Comment by swanidhi** [comment]
Agreed. However native for loop is not very bad to look at either. And the
performance difference is considerable. Hence suggested.

**Comment by bendc** [comment]
What @misbeliever said.
