### ISSUE TITLE
Double quote missing on some HTML property values

### ISSUE THREAD

**Issue by AllThingsSmitty** [bendc/frontend-guidelines#753]
Ben, first, **AWESOME** repo.

Second, I noticed that some of the syntax under the HTML section doesn't contain quotes for all property values. Ex:

``` html
<input type=email placeholder=you@email.com required>
```

In some cases you do include it:

``` html
<input type="email" placeholder="you@email.com" required>
```

For consistency I think you want to keep with one pattern.

**Comment by hstarorg** [comment]
I agree with you.

**Comment by e-cloud** [comment]
Obviously, the author has *left* **github** for a while~~~

**Comment by bendc** [comment]
Fixed -- sorry for the "small" delay 🤭

**Comment by xypnox** [comment]
The current repo code disregards quotes around attributes. The w3c recommends quotes around values.

[[HTML Attributes](https://www.w3schools.com/htmL/html_attributes.asp)](https://www.w3schools.com/htmL/html_attributes.asp)
