### ISSUE TITLE
You can eliminate </html>

### ISSUE THREAD

**Issue by msheakoski** [bendc/frontend-guidelines#8]
In your examples, you stress brevity (and presumably clarity). One thing I do that makes HTML documents easier for me to read is to eliminate the closing `</html>` tag and move the indentation up 1 level, which is still valid HTML5:
```html
<!doctype html>
<html lang=en>
  <meta charset=utf-8>
  <title>Contact</title>
  <link rel=stylesheet href=style.css>

  <h1>Contact me</h1>
  <input type=email placeholder=you@email.com required>
  <script src=main.js></script>
</html>
```
becomes
```html
<!doctype html>
<html lang=en>
<meta charset=utf-8>
<title>Contact</title>
<link rel=stylesheet href=style.css>

<h1>Contact me</h1>
<input type=email placeholder=you@email.com required>
<script src=main.js></script>
```

**Comment by bendc** [comment]
Technically, your code should still be indented, even if you omit the closing html tag. I don't have a strong opinion about this one though, feel free to do whatever you want :)

**Comment by msheakoski** [comment]
Absolutely, just offering my 2¢ in case anybody found it helpful :) I get what you're saying, about indentation. It's definitely a matter of personal preference. When I eliminate closing tags, in most cases I treat them with the same indentation rules I use for <meta>, <link>, <br>, etc...
